In [1]:
from TTLinear import TTLinear

In [2]:
import torch
weights = torch.rand(768, 3072)

In [17]:
a = TTLinear(in_features = 3072, out_features = 768, ranks =[72, 72, 72] , input_dims = [8, 8, 6, 8], output_dims= [4, 6, 8 ,4])

In [4]:
dummy_matrix = torch.randn(weights.shape)
a.set_weight_with_fisher(weights, dummy_matrix)

tensor.shape, fisher_tensor.shape ranks torch.Size([32, 48, 48, 32]) torch.Size([32, 48, 48, 32]) [72, 72, 72]
self.cores shape [torch.Size([1, 32, 32]), torch.Size([32, 48, 1536]), torch.Size([1536, 48, 32]), torch.Size([32, 32, 1])]
self.fcores shape [torch.Size([1, 32, 32]), torch.Size([32, 48, 1536]), torch.Size([1536, 48, 32]), torch.Size([32, 32, 1])]
mu 3
I unfold shape torch.Size([32, 32])
mu 2
I unfold shape torch.Size([1536, 1536])
mu 1
I unfold shape torch.Size([32, 73728])


In [5]:
import tntorch as tn
for core in a.weight.fcores:
    print (core[0][1])
    print (torch.sum(core))
    
    
    IU = tn.right_unfolding(core, batch=False)
    print (IU.shape)
    print (IU.sum(1))
    print ("\n")

tensor([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
tensor(32.)
torch.Size([1, 1024])
tensor([32.])


tensor([[-0.4371,  0.0148,  0.3389,  ...,  0.9550, -0.0140, -1.5719],
        [ 1.3601, -1.5852,  0.2966,  ..., -0.7508, -0.2588, -0.5265],
        [ 1.1834, -0.9826, -0.9369,  ..., -0.0181,  0.8647, -1.1700],
        [-0.1803, -0.0410,  2.6793,  ...,  0.3652,  1.3062,  1.3158],
        [-1.8094, -0.9554,  0.4625,  ...,  0.9075, -1.7894,  0.1916],
        [-1

## Create batch of objects

In [15]:
b = torch.rand(1, 100, 768)
weights = torch.rand(768, 3072)
(b@weights).shape

torch.Size([1, 100, 3072])

In [18]:
a(b)

RuntimeError: shape '[1, 100, 768]' is invalid for input of size 19200

In [ ]:
from ttensor_fisher import CustomTensor

tt = CustomTensor(tensor, fisher_tensor, ranks_tt=ranks, batch=self.batch)